export const actividadesInciales = [
    {
        obligaciones: 'IMPARTIR FORMACIÓN PROFESIONAL INTEGRAL QUE NO SOLO ABARQUE LOS CONOCIMIENTOS TÉCNICO Y ACADÉMICOS, SINO TAMBIÉN LAS HABILIDADES Y ACTITUDES NECESARIAS PARA SU DESEMPEÑO EN EL SECTOR PRODUCTIVO, PROMOVIENDO SU CRECIMIENTO PERSONAL Y PROFESIONAL. ESTE ACOMPAÑAMIENTO SE REALIZARÁ CONFORME A LAS DIRECTRICES Y OBJETIVOS DEL PROGRAMA DE FORMACIÓN, GARANTIZANDO QUE SE DESARROLLEN TANTO LAS COMPETENCIAS ESPECÍFICAS COMO LAS HABILIDADES BLANDAS REQUERIDAS PARA SU ÉXITO EN EL ÁMBITO LABORAL.',
        accionesRealizadas: 'IMPARTIR FORMACIÓN PROFESIONAL EN LOS PROGRAMAS DE FORMACIÓN TITULADA O COMPLEMENTARIA DE ACUERDO CON LA PROGRAMACIÓN ASIGNADA EN LAS SIGUIENTES FICHAS DE CARACTERIZACIÓN:',
        evidencias: 'REPORTE MENSUAL DE INSTRUCTOR (RMI) HTTPS://FORMS.OFFICE.COM/R/EDZYRZGIRY'
    },
    {
        obligaciones: 'EJECUTAR LA PRESTACIÓN DEL SERVICIO COMO INSTRUCTOR SENA, A LOS APRENDICES MATRICULADOS EN LOS PROGRAMAS ASIGNADOS EN LA PROGRAMACIÓN MENSUAL, DESARROLLANDO LAS ACTIVIDADES DE ENSEÑANZA-APRENDIZAJE-EVALUACIÓN, EN EL LUGAR, JORNADA Y MODALIDAD ESTABLECIDOS EN LA FICHA DE CARACTERIZACIÓN.',
        accionesRealizadas: 'EJECUCIÓN DE ACCIONES DE FORMACIÓN PROFESIONAL INTEGRAL DE ACUERDO CON LAS POLÍTICAS Y PROCEDIMIENTOS INSTITUCIONALES.',
        evidencias: 'ACTAS DE TRIMESTRE Y REUNIÓN EQUIPO EJECUTOR GUÍA DE APRENDIZAJE, INSTRUMENTO DE EVALUACIÓN Y MATERIAL DE APOYO REGISTRADO EQUIPOS DE CLASES DE TEAMS PARA CADA FICHA'
    },
    {
        obligaciones: 'REPORTAR NOVEDADES DE APRENDICES PRESENTADAS EN LA EJECUCIÓN DE LA FORMACIÓN DE ACUERDO CON EL REGLAMENTO DE APRENDIZ Y LAS FICHAS ASOCIADAS',
        accionesRealizadas: 'DILIGENCIAR LAS GUÍAS DE APRENDIZAJE, INSTRUMENTOS DE EVALUACIÓN Y MATERIAL DE APOYO PARA LOS APRENDICES EN LOS FORMATOS O INSTRUMENTOS OFICIALES ACTUALIZADOS Y PUBLICARLOS EN EL APLICATIVO COMPROMISO',
        evidencias: 'NO SE REPORTAN NOVEDADES'
    },
    {
        obligaciones: 'EMITIR LOS JUICIOS EVALUATIVOS (CRITERIOS DE EVALUACIÓN) DE LOS APRENDICES PERTENECIENTES A LAS FICHAS EN LAS QUE SE ENCUENTRE ASOCIADO EL CONTRATISTA, DENTRO DE LOS OCHO (8) DÍAS HÁBILES ESTABLECIDOS POR LA 4 NORMATIVIDAD VIGENTE, COMO MECANISMO DE CONTROL DE CALIDAD; REGISTRANDO OPORTUNAMENTE LA VALORACIÓN EN EL SISTEMA DISPUESTO POR LA ENTIDAD (SOFIA PLUS) Y EN LOS MEDIOS REQUERIDOS POR LA COORDINACIÓN ACADÉMICA Y/O SUBDIRECCIONES CENTRO DE FORMACIÓN',
        accionesRealizadas: 'ETAPA LECTIVA: REGISTRAR EN EL APLICATIVO SOFIA PLUS Y EN DIGITAL A QUIEN CORRESPONDE LA EMISIÓN DE JUICIOS DE RESULTADOS DE APRENDIZAJE EVIDENCIADO POR LOS APRENDICES, EN LOS TIEMPOS ESTABLECIDOS POR EL PROCEDIMIENTO DE LA EJECUCIÓN DE LA FORMACIÓN Y REGLAMENTO DEL APRENDIZ. JUICIOS PARA ETAPA LECTIVA',
        evidencias: 'REPORTE DE JUICIOS EVALUATIVOS EL CUAL SE INCLUYEEN EL ARCHIVO DE GESTIÓN CONTRACTUAL DE CADA MES.'
    },
    {
        obligaciones: 'GARANTIZAR EL PAGO OPORTUNO DE LA SEGURIDAD SOCIAL (SALUD, PENSIÓN Y RIESGOS LABORALES) DENTRO DE LOS PRIMEROS DIEZ (10) DÍAS DE CADA MES,',
        accionesRealizadas: 'REALIZO EL PAGO DE APORTES A SEGURIDAD SOCIAL DE LA PLANILLA DE APORTES EN LÍNEA PARA EL MES DE FEBRERO CONFORME A LAS NORMATIVAS VIGENTES.',
        evidencias: 'PLANILLA DE PAGO SEGURIDAD SOCIAL LA CUAL SE INCLUYE EN EL ARCHIVO DE GESTIÓN FINANCIERA DE CADA MES.'
    },
    {
        obligaciones: 'ENTREGAR DE MANERA MENSUAL Y OPORTUNA LOS DOCUMENTOS REQUERIDOS PARA EL TRÁMITE DE PAGO DE LOS HONORARIOS, LOS CUALES SERÁN ALMACENADOS DIGITALMENTE EN EL ESPACIO HABILITADO POR LA COORDINACIÓN ACADÉMICA DEL CENTRO DE COMERCIO Y SERVICIOS. ASEGURARSE DE QUE LA PLANILLA PARA EL PAGO DE HONORARIOS CUMPLA CON LAS DISPOSICIONES VIGENTES O LAS',
        accionesRealizadas: 'SE ELABORÓ EL INFORMÉ PARA EL PRESENTE MES Y DEMÁS DOCUMENTOS REQUERIDOS PARA DAR TRÁMITE AL PAGO DE LOS HONORARIOS.',
        evidencias: 'SE ENVIAN A DRIVE DE OUTLOCK'
    }
];