export const ESTADOS_APERTURA = [
  { value: 'ACTIVO', label: 'Activo' },
  { value: 'INACTIVO', label: 'Inactivo' },
  { value: 'OCULTO', label: 'Oculto' },
  { value: 'PENDIENTE', label: 'Pendiente' },
  { value: 'RECHAZADO', label: 'Rechazado' },
  { value: 'APROBADO', label: 'Aprobado' },
  { value: 'CANCELADO', label: 'Cancelado' },
  { value: 'REPROBADO', label: 'Reprobado' },
  { value: 'CERRADO', label: 'Cerrado' },
  { value: 'ACEPTADO', label: 'Aceptado' },
  { value: 'LEIDO', label: 'Leído' },
  { value: 'EN ESPERA', label: 'En espera' },
  { value: 'INSCRIPCION', label: 'Inscripción' },
  { value: 'MATRICULADO', label: 'Matriculado' },
  { value: 'ABIERTO', label: 'Abierto' },
  { value: 'EN CURSO', label: 'En curso' },
  { value: 'POR ACTUALIZAR', label: 'Por actualizar' },
  { value: 'CURSANDO', label: 'Cursando' },
  { value: 'ENTREVISTA', label: 'Entrevista' },
  { value: 'SIN ENTREVISTA', label: 'Sin entrevista' },
  { value: 'JUSTIFICADO', label: 'Justificado' },
];
